source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VIPERS-Converter-Protocol_Example' do
  pod 'VIPERS-Converter-Protocol', :path => '../'
end

target 'VIPERS-Converter-Protocol_Tests' do
  pod 'VIPERS-Converter-Protocol', :path => '../'
end
